version: 0.2

phases:
  install:
    commands:
      - echo "Instalando Terraform"
      - curl -O https://releases.hashicorp.com/terraform/1.3.0/terraform_1.3.0_linux_amd64.zip
      - unzip terraform_1.3.0_linux_amd64.zip
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "Iniciando Terraform"
      - terraform init

  build:
    commands:
      - echo "Planificando Terraform"
      - terraform plan -out=tfplan

  post_build:
    commands:
      - echo "Aplicando Terraform"
      - terraform apply -auto-approve tfplan

artifacts:
  files:
    - '**/*'
  discard-paths: yes

